name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci || npm install

      # Force Vite to output to ./dist even if vite.config sets a different outDir
      - name: Build
        run: npm run build -- --outDir dist --emptyOutDir

      - name: Debug build output
        run: |
          echo "Root contents:"
          ls -la
          echo "dist contents (if any):"
          if [ -d dist ]; then ls -la dist; else echo "dist/ not found"; fi

      - name: Create 404 fallback for SPA
        run: |
          if [ -f dist/index.html ]; then
            cp dist/index.html dist/404.html
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



